blank_issues_enabled: false
contact_links:
 - name: 📚 Documentation
   url: https://github.com/dbfast/dbfast-cli#readme
   about: Check if your question is answered in the docs
 - name: 💬 GitHub Discussions
   url: https://github.com/dbfast/dbfast-cli/discussions
   about: Ask questions and discuss with other community members